# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Ea9ZuoNtetPMxycCPvMA4l5CdcP6d3r
"""

from cvxpy import *
import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

A = np.array([[10,5],[3,5]]).T
b = np.array([14,7]).reshape((2,-1 ))
c = np.array([6,5])

x = Variable((2,1),nonneg = True)

f = c@x
obj = Minimize(f)
# Constraints
constraints = [A.T@x >= b]
Problem(obj, constraints).solve()

print("Minimum_value: " ,(f.value))
print("attained at: ",(x.value))

#Generating and plotting line 10x+5y = 14
A=np.array([5,-1.8])
B=np.array([-1.8,3.4])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='10x+5y=14')

#Generating and plotting line 3x+5y = 7
C=np.array([-0.5,6.7])
D=np.array([3,-1.8])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='3x+5y=7')

#Shading Required Region
x1=[C[0],8/3,A[0],2]
y1=[C[1],11/2,A[1],1/2]
plt.fill(x1,y1,color="gray",alpha=0.7)

#Labelling points
plt.plot(2,1/2,'o',color='r')
plt.text(2,1,'A(2,1/2)')

plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')